### ISSUE TITLE
Tags on blog posts

### ISSUE THREAD

**Issue by Tehnix** [Tehnix/HsCMS#13]
Comma separated list in the bottom. Auto create new tags from this list, if they don't exist in advance. If a post already has tags, they will display a little x, so you can delete them. 

Use a relational database setup. Table with tags (id, name) and table linking tags to blog posts (tag_id, blog_id).

**Comment by ghost** [comment]
Is there a good reason not to just store the tag's name directly as a string? What are SQLite's indexing performance properties?

**Comment by Tehnix** [comment]
By having a table separately for tags and for the relation to blog posts we get the benefit of:
- not creating duplicate tags
- if a tag name is changed, if reflects on all the places it's used

the latter might not happen very often of course.

It also gets easier to add meta data to tags and other information later on, instead of polluting the Article table with such information. Articles in themself have no knowledge of tags, since that is taken care of by the relation table.
